version: '3.8'
volumes:
  database:
services:
  passx-spring:
    container_name: passx-spring
    image: passx-spring
    restart: on-failure
    depends_on:
      - passx-mysql
    build: .
    ports:
      - "8443:8443"
    environment:
      MYSQL_HOST: passx-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  passx-mysql:
    container_name: passx-mysql
    image: mysql
    volumes:
      -  database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: passx
      MYSQL_ROOT_PASSWORD: root
